appenders:
  rollingfile:
    kind: rolling_file
    path: "log/rolling_file.log"
    policy:
      trigger:
        kind: size
        limit: 3mb
      roller:
        kind: delete
root:
  level: info
  appenders:
    - rollingfile
