services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER?error}
      POSTGRES_PASSWORD: ${DB_PASSWORD?error}
      POSTGRES_DB: ${DB_NAME?error}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
volumes:
  pgdata_dev:
